<?php
/**
 * About page
 */
// Hack, see http://help.slimframework.com/discussions/questions/4686-slimviewsetdata-protects-closures
$title  = $title();
$title('About me');
?>
<section itemscope itemtype="http://schema.org/Person">
    <h1>
        <a href="<?= $app->urlFor('home')?>"><span itemprop="name">Jurian Sluiman</span></a>
        &middot;
        <a href="<?= $app->urlFor('about')?>">about me</a>
    </h1>

    <p itemprop="description">My name is Jurian Sluiman, a Dutch health care consultant, occasional blogger and happy music lover. I obtained a masters degree in Biomedical Engineering at Delft University of Technology and have expertise in entrepreneurship, building scalable software applications and establishing successful commercial propositions.</p>

    <p><q>My goal is to create novel concepts, creating societal value for things that matter</q></p>

    <p>Always in a search for innovation, I continuously explore the world behind the borders of my current knowledge. The pragmatic focus caused me to work with many people full of ideas. For me, the joy of life is to turn every good idea into a working product or service.</p>

    <h2>Experience</h2>
    <ul class="about-experience">
        <li><strong>Health care consultant</strong> Buitenhuis Advies (2015 - present)</li>
        <li><strong>Founder and entrepreneur</strong> Soflomo (2009 - 2014)</li>
        <li><strong>Intern</strong> Maquet GmbH &amp; CO. KG, Rastatt, Germany (2011)</li>
        <li><strong>Founder</strong> Librio (2010 - 2011)</li>
    </ul>

    <h2>Education</h2>
    <ul class="about-education">
        <li><strong>Launchlab</strong>, YES!Delft (2013)</li>
        <li><strong>Biomedical Engineering</strong>, MSc (2012), Delft University of Technology</li>
        <li><strong>Mechanical Engineering</strong>, BSc (2010), Delft University of Technology</li>
        <li><strong>Gymnasium</strong>, high school (2005), Sint Maartenscollege Voorburg</li>
    </ul>
</section>
