<?php
/**
 * Layout
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?= $title->append('Jurian Sluiman')?></title>
    <?= $meta ?>
    <meta name="viewport"  content="width=device-width, initial-scale=1">
    <link href="/styles/dist/styles.css" media="screen" rel="stylesheet" type="text/css">
</head>

<body itemscope itemtype="http://schema.org/WebPage">
    <div class="admin-bar">
        <nav>
            <a href="<?= $app->urlFor('admin')?>"><img src="/styles/icons/admin-icon.svg" class="logo">admin</a>
            <a href="<?= $app->urlFor('admin-blog')?>">blog</a>
            <a href="<?= $app->urlFor('admin-blog-create')?>">create article</a>
            <a href="<?= $app->urlFor('home')?>" target="_blank">back home &#8625;</a>
        </nav>
    </div>

    <main role="main" class="container"><?= $yield?></main>

    <?=  $script->prepend('/scripts/dist/admin.js') ?>
</body>
</html>
