<h1 style="font-size:12rem;line-height:1;margin-bottom:0;">Oh no!</h1>

<p>
    An error occurred during execution; please try again later.
    <?php if (isset($exception)):?>
        <code><?= get_class($exception)?></code>: <?= $exception->getMessage()?>
    <?php endif?>
</p>

<p>
    <a href="http://www.flickr.com/photos/hikingartist/5727425824/"><img src="http://farm4.staticflickr.com/3259/5727425824_0d42007863_b.jpg" class="full-width"></a><br>
    <em>Image courtesy of Frits Ahlefeldt, <a href="http://hikingartist.com">hikingartist.com</a></em>
</p>

<p>Please <a href="/contact">let me know</a> what happened, so I can fix this problem.</p>
