<?php
/**
 * Paginator with archived blog articles
 */
$currentDate = null;
?>
<h1><a href="/">Jurian Sluiman &middot; archived posts</a></h1>

<section itemscope itemtype="http://schema.org/Blog">
    <?php foreach ($articles as $article):?>
        <?php if (($date = date('F Y', $article['date'])) !== $currentDate): ?>
            <?php if ($currentDate !== null):?></ul><?endif?>
            <h2 class="blog-archive-publishdate">
                <time datetime="<?= date('c', $article['date'])?>"><?= $date?></time>
            </h2>
            <ul class="blog-archive-listing">
        <?php $currentDate = $date?>
        <?php endif?>

        <?php $url = $app->urlFor('article', ['id' => $article['id'], 'slug' => $app->slugifier->slugify($article['title'])]) ?>
        <li><span itemprop="name" class="blog-archive-title">
            <a href="<?= $url?>" itemprop="url"><?= $article['title']?></a>
        </span></li>
    <?php endforeach ?>
    </ul>

    <div class="row blog-archive-paginator">
        <div class="one-half column prev">
        <?php if ($page !== 1): ?>
            <a href="<?= $app->urlFor('archive', ['page' => $page-1])?>">newer posts</a>
        <?php else : ?>
            &nbsp;
        <?php endif ?>
        </div>

        <div class="one-half column next">
        <?php if ($page !== $pages): ?>
            <a href="<?= $app->urlFor('archive', ['page' => $page+1])?>">older posts</a>
        <?php endif ?>
        </div>
    </div>
</section>
