<?php
/**
 * Blog article page to view a single article
 */
$app->view->setData('title', $article['title']);
?>
<article itemscope itemtype="http://schema.org/BlogPosting">
    <header>
        <h1 itemprop="name" class="blog-article-title">
            <a href="<?= $app->urlFor('article', ['id' => $article['id']])?>" itemprop="url"><?= $article['title']?></a>
        </h1>
        <time datetime="2014-12-02T21:00:00+01:00" pubdate itemprop="datePublished" content="2014-12-02T21:00:00+01:00" title="2014-12-02 21:00:00" class="blog-article-publishdate">December 2014</time>
    </header>

    <?= $article['lead']?>
    <?= $article['body']?>
</article>
