<?php
/**
 * Blog article page to view a single article
 */
$desc   = trim(strip_tags($article['lead']));

$title->prepend($article['title']);
$meta->append('description', $desc);
$meta->append('twitter:card', 'summary');
$meta->append('twitter:creator', '@juriansluiman');
$meta->append('twitter:title', $article['title']);
$meta->append('twitter:description', $desc);

$script->append('/scripts/dist/prism.js');
$script->append('//fb.me/react-0.12.2.js');
$script->append('//fb.me/JSXTransformer-0.12.2.js');
$script->append('//code.jquery.com/jquery-1.10.0.min.js');
$script->append('//cdnjs.cloudflare.com/ajax/libs/showdown/0.3.1/showdown.min.js');
$script->append('/scripts/src/comments.js', null, 'text/jsx');
?>
<article itemscope itemtype="http://schema.org/BlogPosting" class="blog-article" id="content">
    <header>
        <h1 itemprop="name" class="blog-article-title">
            <a href="<?= $app->urlFor('article', ['id' => $article['id']])?>" itemprop="url"><?= $article['title']?></a>
        </h1>
        <time datetime="2014-12-02T21:00:00+01:00" pubdate itemprop="datePublished" content="2014-12-02T21:00:00+01:00" title="2014-12-02 21:00:00" class="blog-article-publishdate">December 2014</time>
    </header>

    <?= $article['lead']?>
    <span id="body"></span>
    <?= $article['body']?>
</article>
