<?php
/**
 * Blog article page to view a single article
 */
// Hack, see http://help.slimframework.com/discussions/questions/4686-slimviewsetdata-protects-closures
$title  = $title();
$meta   = $meta();
$script = $script();
$desc   = strip_tags($article['lead']);

$title($article['title']);
$meta('description', $desc);
$meta('twitter:card', 'summary');
$meta('twitter:creator', '@juriansluiman');
$meta('twitter:title', $article['title']);
$meta('twitter:description', $desc);

$script('/scripts/dist/prism.js');
?>
<article itemscope itemtype="http://schema.org/BlogPosting">
    <header>
        <h1 itemprop="name" class="blog-article-title">
            <a href="<?= $app->urlFor('article', ['id' => $article['id']])?>" itemprop="url"><?= $article['title']?></a>
        </h1>
        <time datetime="2014-12-02T21:00:00+01:00" pubdate itemprop="datePublished" content="2014-12-02T21:00:00+01:00" title="2014-12-02 21:00:00" class="blog-article-publishdate">December 2014</time>
    </header>

    <?= $article['lead']?>
    <span id="body"></span>
    <?= $article['body']?>
</article>
