<h1 style="font-size:12rem;line-height:1;margin-bottom:0;">Oops!</h1>

<p>My bad, the page you were looking for cannot be found.</p>

<p>
    <a href="https://www.flickr.com/photos/hikingartist/8287082967/"><img src="http://farm9.staticflickr.com/8357/8287082967_58eef6b2cb_b.jpg" class="full-width"></a><br>
    <em>Image courtesy of Frits Ahlefeldt, <a href="http://hikingartist.com">hikingartist.com</a></em>
</p>

<p>If you got here by following a link from outside this website then that link may be out of date. Your best bet is to go back to the <a href="<?= $app->urlFor('home')?>">home page</a> and browse from there.</p>

<p>If the bad link was within the this website then I screwed up and I would appreciate it if you could <a href="<?= $app->urlFor('contact')?>">let me know</a>.</p>
