<?php
/**
 * Contact page
 */
?>
<section class="blog-article about-me">
    <h1>
        <a href="<?= $app->urlFor('home')?>">Jurian Sluiman</a>
        &middot;
        <a href="<?= $app->urlFor('contact')?>">contact me</a>
    </h1>

    <p>You can always contact me via <a href="mailto:jurian@juriansluiman.nl">jurian@juriansluiman.nl</a>. Additionally, I am registered on several social networks you can use to get in touch.</p>

    <p class="contact-socials">
        <a href="https://twitter.com/juriansluiman"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
        <a href="https://plus.google.com/+JurianSluiman"><i class="fa fa-google-plus fa-fw fa-3x"></i></a>
        <a href="https://linkedin.com/in/juriansluiman"><i class="fa fa-linkedin fa-fw fa-3x"></i></a>
        <a href="https://github.com/juriansluiman"><i class="fa fa-github fa-fw fa-3x"></i></a>
    </p>

    <p>If you want to send me a message privately, you can use <a href="https://keybase.io/jurian">keybase.io</a>. My key has the following fingerprint: <code>043BE0446A206379</code>. It allows you to send me an encrypted message no other person can read. If you do not use keybase.io or has no GPG key, you can use <a href="https://keybase.io/encrypt#jurian">a dedicated webpage</a> to send me an encrypted message.</p>
</section>

<style>
.contact-socials a {
    display: inline-block;
    width: 24%;
    text-align: center;
}
.contact-socials i:hover {
    text-decoration: underline;
}
</style>
