<?php
/**
 * Layout
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?= $title->append('Jurian Sluiman')?></title>
    <?= $meta ?>
    <meta name="copyright" content="Jurian Sluiman 2006-2015">
    <meta name="generator" content="http://github.com/juriansluiman.nl">
    <meta name="viewport"  content="width=device-width, initial-scale=1">
    <link rel='alternate' type='application/rss+xml' title='RSS feed of juriansluiman.nl' href='<?= $app->urlFor('feed')?>'>
    <link href="/styles/dist/styles.css" media="screen" rel="stylesheet" type="text/css">
</head>

<body itemscope itemtype="http://schema.org/WebPage">
    <main role="main" class="container"><?= $yield?></main>

    <footer role="contentinfo" class="container page-footer">
        <p>&copy; Jurian Sluiman 2006-2015 &mdash; All content is licensed under the <a href="https://creativecommons.org/licenses/by-sa/3.0/">Creative Commons BY-SA 3.0</a> unless otherwise stated.</p>

        <ul class="row footer-nav">
            <li class="one-third column"><a href="<?= $app->urlFor('home')?>">blog</a></li>
            <li class="one-third column"><a href="<?= $app->urlFor('about')?>">about me</a></li>
            <li class="one-third column"><a href="<?= $app->urlFor('contact')?>">contact</a></li>
        </ul>
    </footer>

    <?php
    if (count($flash)) {
        foreach ($flash->getMessages() as $message) {
            $script->append(null, sprintf('humane.log("%s")', $message));
        }
    }

    echo $script->prepend('/scripts/dist/main.js') ?>

    <?php if ($admin):?>
        <div style="position: fixed; right: 0.3em; bottom: 0.3em;"><a href="<?= $app->urlFor('admin')?>"><img src="/styles/icons/admin-icon.svg" class="logo" style="height: 2em;"></a></div>
    <?php endif ?>
</body>
</html>
