<?php
/**
 * Layout
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?= $title->append('Jurian Sluiman')?></title>
    <?= $meta ?>
    <meta name="copyright" content="Jurian Sluiman 2006-2015">
    <meta name="generator" content="http://github.com/juriansluiman.nl">
    <meta name="viewport"  content="width=device-width, initial-scale=1">
    <link href="https://plus.google.com/102726331143136952916?rel=author" rel="author">
    <link rel='alternate' type='application/rss+xml' title='RSS feed of juriansluiman.nl' href='<?= $app->urlFor('feed')?>'>
    <link href="/styles/dist/styles.css" media="screen" rel="stylesheet" type="text/css">
</head>

<body itemscope itemtype="http://schema.org/WebPage">
    <main role="main" class="container"><?= $yield?></main>

    <footer role="contentinfo" class="container page-footer">
        <p>&copy; Jurian Sluiman 2006-2015 &mdash; All content is licensed under the <a href="https://creativecommons.org/licenses/by-sa/3.0/">Creative Commons BY-SA 3.0</a> unless otherwise stated.</p>

        <ul class="row footer-nav">
            <li class="one-third column"><a href="<?= $app->urlFor('home')?>">blog</a></li>
            <li class="one-third column"><a href="<?= $app->urlFor('about')?>">about me</a></li>
            <li class="one-third column"><a href="<?= $app->urlFor('contact')?>">contact</a></li>
        </ul>
    </footer>

    <?= $script->append(null, <<<SCRIPT
WebFontConfig = {
  google: { families: [ 'Source Code Pro' ] }
};

(function() {
  var wf = document.createElement('script');
  wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
           '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
  wf.type = 'text/javascript';
  wf.async = 'true';

  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(wf, s);
})();
SCRIPT
) ?>
</body>
</html>
