<?php
/**
 * Login token form
 */
?>

<section>
    <h1>Login request</h1>

    <form method="post" action="<?= $app->urlFor('login')?>" id="login-form">
        <input type="hidden" name="csrf" value="<?= $csrf ?>">
        <button type="submit" id="login-form-button">Request login</button>
    </form>
</section>

<script>
document.querySelector('form').addEventListener('submit', function() {
    var button = document.querySelector('form button[type="submit"]');
    button.disabled  = true;
    button.innerText = 'Requesting...';
});
</script>
